/**
 * Post-mortem document generation
 */

import * as core from '@actions/core';

export interface PostMortemData {
  incidentId: string;
  serviceName: string;
  timestamp: string;
  errorMessage: string;
  stackTrace?: string;
  diagnosis: string;
  fixDescription: string;
  testResults?: string;
}

/**
 * Generate a post-mortem document
 * @param data - Post-mortem data
 * @returns Formatted post-mortem document
 */
export function generatePostMortem(data: PostMortemData): string {
  core.info('Generating post-mortem document');
  
  const postMortem = `# Post-Mortem: Incident ${data.incidentId}

## What Broke

**Service**: ${data.serviceName}
**Timestamp**: ${data.timestamp}
**Incident ID**: ${data.incidentId}

### Error Message
\`\`\`
${data.errorMessage}
\`\`\`

${data.stackTrace ? `### Stack Trace
\`\`\`
${data.stackTrace}
\`\`\`
` : ''}

## Why It Broke

${data.diagnosis}

## How the Fix Addresses It

${data.fixDescription}

${data.testResults ? `## Test Results

${data.testResults}
` : `## Test Results

No automated tests were run. Manual verification is recommended.
`}

---
*This post-mortem was automatically generated by the AI SRE Platform.*
`;

  return postMortem;
}

/**
 * Validate that a post-mortem contains all required sections
 * @param postMortem - The post-mortem document to validate
 * @returns True if valid, false otherwise
 */
export function validatePostMortem(postMortem: string): boolean {
  const requiredSections = [
    'What Broke',
    'Why It Broke',
    'How the Fix Addresses It',
    'Test Results',
  ];
  
  for (const section of requiredSections) {
    if (!postMortem.includes(section)) {
      core.warning(`Post-mortem missing required section: ${section}`);
      return false;
    }
  }
  
  return true;
}
